/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fisei;

import bd.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Materia extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    String[] ids;
    DefaultComboBoxModel pofesoresModel = new DefaultComboBoxModel();
    DefaultComboBoxModel carrerasModel = new DefaultComboBoxModel();
    String doc;
    Integer fila;
    Conexion cc = new Conexion();
    Connection cn = cc.conectar();
    public Materia() {
        initComponents();
        cargarProfesores();
        cargarCarreras();
        cargarTablaMaterias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreMateria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profesores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        carreras = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        materias = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(nombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 201, -1));

        jLabel1.setText("Nombre de la materia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setText("Profesor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 98, -1, -1));

        getContentPane().add(profesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 123, 201, -1));

        jLabel3.setText("Carrera");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 161, -1, -1));

        getContentPane().add(carreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 186, 201, -1));

        jButton1.setText("Agregar nuevo");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 283, 220, 30));

        materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(materias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 11, 442, -1));

        jButton2.setText("Editar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 105, 30));

        jButton3.setText("Borrar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 105, 30));

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMateriaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Pantalla_gestion pg = new Pantalla_gestion();
        pg.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> carreras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable materias;
    private javax.swing.JTextField nombreMateria;
    private javax.swing.JComboBox<String> profesores;
    // End of variables declaration//GEN-END:variables

    private void cargarProfesores() {
        int i=0;
        try {
            String sql = "select * from docentes";
            Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                i++;
            }
            String[] docentesList = new String[i];
            rs = psd.executeQuery(sql);
            i = 0;
            while (rs.next()) {
                docentesList[i] =  rs.getString("nombre");
                    i++;
                
            }
             pofesoresModel =  new DefaultComboBoxModel(docentesList);
             profesores.setModel(pofesoresModel);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No hay docentes que mostrar");
        }
    }
    
    private void cargarCarreras() {
        int i=0;
        try {
            String sql = "select * from carrera";
            Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                i++;
            }
            String[] carrerasList = new String[i];
            rs = psd.executeQuery(sql);
            i = 0;
            while (rs.next()) {
                carrerasList[i] =  rs.getString("nombre");
                    i++;
                
            }
             carrerasModel =  new DefaultComboBoxModel(carrerasList);
             carreras.setModel(carrerasModel);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No hay carreras que mostrar");
        }
    }
    
    public void cargarTablaMaterias() {
        try {
            String[] titulos = {"#", "Materia", "Docente", "Carrera"};
            String[] materiasList = new String[4];
            modelo = new DefaultTableModel(null, titulos);
            String sql = "select * from materia";
            Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                materiasList[0] = rs.getString("id");
                materiasList[1] = rs.getString("nombre");
                materiasList[2] = rs.getString("docenteID");
                materiasList[3] = rs.getString("carreraID");
                modelo.addRow(materiasList);
            }
            materias.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void cargarTextos(){
        materias.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (materias.getSelectedRow() != -1) {
                    fila = materias.getSelectedRow();
                    nombreMateria.setText(materias.getValueAt(fila, 0).toString());
                    desbloquearBotonesEditarEliminar();
                    desbloquearTextosEditarEliminar();
                }
            }

            private void desbloquearBotonesEditarEliminar() {
            }

            private void desbloquearTextosEditarEliminar() {
            }
        });
    }
}
